### ISSUE TITLE
[Suggestion] Remove NEUTRAL

### ISSUE THREAD

**Issue by jaydevelopsshit** [Fabric-Utility-Mods/Universal-Friends-API#3]
I don't see the point in Neutral, wouldn't all players be neutral by default?

**Comment by seasnail8169** [comment]
It clearly is a useful feature, it allows for identification in things like ESP and Tracers as well as prioritisation in combat modules, to give a few examples. You do not *have* to use these friend types but you can if you want.

**Comment by jaydevelopsshit** [comment]
That is a good point but I still think neutral is really pointless.

**Comment by Vonr** [comment]
NEUTRAL was just a way to return a non-null value for a uuid without an entry

**Comment by jaydevelopsshit** [comment]
Updated the original issue title and desc.

**Comment by Vonr** [comment]
its basically just so that clients dont have to deal with null safety for type and now with the priority system they will get 0 instead of null.

**Comment by RemainingToast** [comment]
NEUTRAL is purely to not return null and neutral players won't be saved to config and I see it being useful as it's neither friend nor enemy

**Comment by jaydevelopsshit** [comment]
Alright, I'm gonna close the issue.
